# Chart source:  https://github.com/Addyvan/valheim-k8s
worldName: cheese
serverName: cheese

passwordSecret: valheim-password

storage:
  kind: hostvol
  hostvol:
    path: /media/chungus/valheim-server

serverStorage:
  hostvol:
    path: /media/chungus/valheim-server

