# values.yaml for kube-prometheus-stack
# Official chart https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

namespaceOverride: "monitoring"

prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: cold-storage
          accessModes: 
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

    resources:
      requests:
        cpu: 200m
        memory: 512Mi
      limits:
        memory: 2Gi

# -- Grafana configuration
grafana:
  # Grafana uses this to map cookies after login and OAuth callbacks, have to specify where requests will come from
  # In a more production setting w/ more users, we can instead use an Ingress URL
  grafana.ini:
    server:
      root_url: "http://192.168.68.78:32403/"
  # Why this https://github.com/grafana/helm-charts/issues/752
  # Tldr its a permissions check to see if grafana can write to it
  initChownData:
    enabled: false

  persistence:
    enabled: true
    storageClassName: cold-storage
    accessModes:
      - ReadWriteOnce
    size: 5Gi

  service:
    type: NodePort
    nodePort: 32403 


  # adminPassword: "changeme"

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: cold-storage   # <-- same storageClass
          accessModes: 
            - ReadWriteMany
          resources:
            requests:
              storage: 2Gi

# -- node-exporter runs as a DaemonSet — no changes needed for single node
nodeExporter:
  enabled: true

# -- kube-state-metrics for deployment/pod health
kubeStateMetrics:
  enabled: true

# -- k3s uses its own etcd/scheduler/controller — disable the kube components
# that aren't exposed in a standard k3s install to avoid broken scrape targets
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false
kubeProxy:
  enabled: false