githubConfigUrl: "https://github.com/saxenavinayak/sugar-lane"

runnerScaleSetName: "self-hosted-runners"

namespaceOverride: "arc-runners"

maxRunners: 1

githubConfigSecret: gh-secret

# We need a podspec to mount a cert so the runners can interact with argocd
# Discussion here https://github.com/actions/actions-runner-controller/discussions/945
template:
  spec:
    volumes:
      - name: argocd-cert
        secret:
          secretName: "argocd-cert-secret"
    containers:
      - name: runner
        image: ghcr.io/actions/actions-runner:latest
        command: ["/home/runner/run.sh"]
        env:
          - name: NODE_EXTRA_CA_CERTS
            value: /etc/argocd-cert/argo-cert.crt
        volumeMounts:
          - name: argocd-cert
            mountPath: /etc/argocd-cert/argo-cert.crt
            subPath: argo-cert.crt # This is a location of the secret (ie., tells kube to look at mySecret.argo-cert\.crt instead of the whole value)
