apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex-deployment
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker:latest
        env:
        - name: PLEX_CLAIM
          value: "claim-XXX"
        ports:
        - containerPort: 32400
        volumeMounts:
        - mountPath: /config
          name: plex-reserve
          subPath: config
        - mountPath: /media
          name: plex-reserve
          subPath: media
      volumes:
        - name: plex-reserve
          persistentVolumeClaim:
            claimName: plex-reserve-claim
