apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-claim-config
spec:
  volumeName: plex-config
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1500Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-claim-media
spec:
  volumeName: plex-media
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1500Gi
  storageClassName: local-storage