apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-reserve-claim
spec:
  volumeName: plex-reserve
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1500Gi
  storageClassName: local-storage
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: plex-claim-media
# spec:
#   volumeName: plex-media
#   accessModes:
#     - ReadWriteOnce
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 1500Gi
#   storageClassName: local-storage