apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: switches
  name: switch-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: switches
  template:
    metadata:
      labels:
        app: switches
    spec:
      containers:
      - env:
        - name: KASA_USERNAME
          valueFrom:
            secretKeyRef:
              key: kasa-username
              name: kasa-creds
        - name: KASA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: kasa-password
              name: kasa-creds
        image: saxenavinayak/sugar-lane:e6155defd404146a03f4586c2d87323014618516
        imagePullPolicy: Always
        name: switch
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
