name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted-runners
    steps:
    - name: Install ArgoCD CLI
      uses: clowdhaus/argo-cd-action/@main
      with:
        download-url: "https://argocd-server.argocd.svc.cluster.local/download/argocd-linux-amd64"
        command: version
        options: --client
    - name: Deploy application
      uses: clowdhaus/argo-cd-action/@main
      with:
        command: app sync immich
        options: >-
          --auth-token ${{ secrets.ARGO_CI_CD_TOKEN }}
          --server ${{ secrets.ARGOCD_SERVER }}
          --grpc-web
          --server-crt /etc/argocd-cert/argo-cert.crt