name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted-runners
    steps:
    - name: Install ArgoCD CLI
      uses: clowdhaus/argo-cd-action/@main
      with:
        download-url: "http://argocd-server.argocd.svc.cluster.local/download/argocd-linux-amd64"
        command: version
        options: --client
